### ISSUE TITLE
关于Component封装

### ISSUE THREAD

**Issue by QinZhen001** [beautywe/beautywe#10]
你好，我尝试使用这个框架对原生Component函数进行封装，发现Object.defineProperty中_theHost会有指向问题，所以就没有办法对Component进行封装了吗？

**Comment by JerryC8080** [comment]
对于 Component 的支持，在项目初始的阶段是计划的。但后面发现，在我遇到的绝大多数的场景下，对于 Page 的插件化已经能满足需求了，所以没有对 Component 进行开发和测试。

然后，能方便告知一下，你这边的场景是怎么样的么？或许有哪些是我考虑不周全的。

**Comment by QinZhen001** [comment]
我这边需要在页面中使用一些behaviors，所以会将页面以Component的形式呈现。
```
Component({
  behaviors: [],
  data: {},
  methods: {
    onLoad(options) {
    },
    onShow() {

    },
    onHide() {
    },
    toDetail(e) {
    },
    ......
  },
});
```

**Comment by JerryC8080** [comment]
我明白了，我会放到后面的迭代计划中来考虑对 Component 的支持。

**Comment by QinZhen001** [comment]
:clap::clap::clap:
