### ISSUE TITLE
这个项目不维护，放弃了吗？

### ISSUE THREAD

**Issue by lsw1990** [beautywe/beautywe#8]
已经2个月没有维护了，此项目不再进行维护了吗？
能否加入链式的微信自带的api啊

**Comment by JerryC8080** [comment]
还在维护的，后续的迭代计划，还在思考中。在这里，可以看到后续迭代的功能池：[Idea Pool](https://github.com/orgs/beautywe/projects/2)
对于微信自带的 API 进行链式支持，的确可以支持，难度也不大。

BTW，其实 2 个月没有 commit ≠ 不维护了。
