### ISSUE TITLE
beautywe.min.js如何用插件？

### ISSUE THREAD

**Issue by lsw1990** [beautywe/beautywe#9]
beautywe.min.js如何用插件？

**Comment by JerryC8080** [comment]
的确，目前 beautywe.min.js 支持用户自定义插件，但是要引入官方插件的min，还是要各自插件提供 min 版本。
目前官方插件的还不支持 min 版本，我还在思考插件的构建过程，做到更加的小的代码量。
然后，官方插件的min版本，我加到后面的迭代上面来了。[Update #003](https://github.com/orgs/beautywe/projects/4)
